<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"  />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"  />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FairShare.Application\FairShare.Application.csproj" />
    <ProjectReference Include="..\FairShare.Infrastructure\FairShare.Infrastructure.csproj" />
  </ItemGroup>

</Project>
